### ISSUE TITLE
Unable to extract files from APF

### ISSUE THREAD

**Issue by JonJon565** [SuRGeoNix/APF#1]
Hello sir can you possibly give a Demo script for extracting files in a APF file?
There is really no Documation but i tried using this script but it didn't work out
i kept getting this Error
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1674	'Partfile': type used in a using statement must be implicitly convertible to 'System.IDisposable'.	ConsoleApp1	C:\Users\evont\source\repos\ConsoleApp1\ConsoleApp1\Program.cs	19	Active
`

using System;
using System.IO;
using SuRGeoNix.Partfiles;

class Program
{
    static void Main()
    {
        string sourceFilePath = @"C:\Program Files\WindowsApps\VectorUnit.BeachBuggyRacing_1.2.7.0_x64__hvbhrzr8672s2\Assets.apf";
        string destinationFolderPath = @"C:\APF";

        if (!Directory.Exists(destinationFolderPath))
        {
            Directory.CreateDirectory(destinationFolderPath);
        }

        try
        {
            using (Partfile partfile = new Partfile(sourceFilePath))
            {
                using (PartStream partStream = partfile.GetReadStream())
                {
                    byte[] buffer = new byte[4096];

                    using (FileStream destinationFileStream = File.Create(Path.Combine(destinationFolderPath, partfile.Filename)))
                    {
                        int bytesRead;
                        while ((bytesRead = partStream.Read(buffer, 0, buffer.Length)) > 0)
                        {
                            destinationFileStream.Write(buffer, 0, bytesRead);
                        }
                    }
                }
            }

            Console.WriteLine("Export completed successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}

**Comment by JonJon565** [comment]
using System;
using System.IO;
using SuRGeoNix.Partfiles;

class Program
{
    static void Main()
    {
        string sourceFilePath = @"C:\Program Files\WindowsApps\VectorUnit.BeachBuggyRacing_1.2.7.0_x64__hvbhrzr8672s2\Assets.apf";
        string destinationFolderPath = @"C:\APF";

        if (!Directory.Exists(destinationFolderPath))
        {
            Directory.CreateDirectory(destinationFolderPath);
        }

        try
        {
            using (Partfile partfile = new Partfile(sourceFilePath))
            {
                using (PartStream partStream = partfile.GetReadStream())
                {
                    byte[] buffer = new byte[4096];

                    using (FileStream destinationFileStream = File.Create(Path.Combine(destinationFolderPath, partfile.Filename)))
                    {
                        int bytesRead;
                        while ((bytesRead = partStream.Read(buffer, 0, buffer.Length)) > 0)
                        {
                            destinationFileStream.Write(buffer, 0, bytesRead);
                        }
                    }
                }
            }

            Console.WriteLine("Export completed successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}

**Comment by SuRGeoNix** [comment]
Hi @JonJon565, I've made this lib mainly for BitSwarm so didn't really have any documentation. You can see how BitSwarm using it [here](https://github.com/SuRGeoNix/BitSwarm/blob/master/BitSwarm/BEP/Torrent.cs)

The error that you get is that Partfile even if I have a Dispose there it does not implement IDisposable. So, instead of using use try catch and just call dispose.
